//
//  DetailPresenter.swift
//  ExsampleAppCoordinator
//
//  Created by Komsit on 20/11/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentGetParam(response: Detail.GetParam.Response)
}

final class DetailPresenter: DetailPresentationLogic {
	weak var viewController: DetailDisplayLogic?
	
    func presentGetParam(response: Detail.GetParam.Response) {
        let viewModel = Detail.GetParam.ViewModel(param: response.param)
        viewController?.displayParam(viewModel: viewModel)
    }
}
