//
//  DetailInteractor.swift
//  ExsampleAppCoordinator
//
//  Created by Komsit on 20/11/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func initial()
}

protocol DetailDataStore {
	var param: String { get set }
}

final class DetailInteractor: DetailBusinessLogic, DetailDataStore {
	var presenter: DetailPresentationLogic?
	var worker: DetailWorker?
    var param: String = ""
	
	// MARK: Init
    func initial() {
        let response = Detail.GetParam.Response(param: param)
        presenter?.presentGetParam(response: response)
    }
}
