//
//  SplashRouter.swift
//  ExsampleAppCoordinator
//
//  Created by Komsit on 18/11/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashRoutingLogic {
    func routeToHome()
}

protocol SplashDataPassing {
	var dataStore: SplashDataStore? { get }
}

protocol SplashCoordinator {
    var coordinator: AppCoordinator? { get set }
}

final class SplashRouter: NSObject, SplashRoutingLogic, SplashDataPassing, SplashCoordinator {
	weak var viewController: SplashViewController?
    weak var coordinator: AppCoordinator?
	var dataStore: SplashDataStore?
	
	// MARK: Routing
    func routeToHome() {
        if let coordinator = coordinator {
            coordinator.goToHome()
        }
    }
}

