//
//  SplashViewController.swift
//  ExsampleAppCoordinator
//
//  Created by Komsit on 18/11/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashDisplayLogic: AnyObject {
	func displayRootView(viewModel: Splash.CheckRootScreen.ViewModel)
}

final class SplashViewController: UIViewController, SplashDisplayLogic, Storyboarded {
	var interactor: SplashBusinessLogic?
	var router: (NSObjectProtocol & SplashRoutingLogic & SplashDataPassing & SplashCoordinator)?

	// MARK: Object lifecycle

	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
        title = "Splash View"
	}
	
	private func setup() {
		let viewController = self
		let interactor = SplashInteractor()
		let presenter = SplashPresenter()
		let router = SplashRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	// MARK: View lifecycle
	override func viewDidLoad() {
		super.viewDidLoad()
        checkNextScreen()
	}
    
    private func checkNextScreen() {
        interactor?.verifyNextScreen(request: Splash.CheckRootScreen.Request())
    }
	
	// MARK: SplashDisplayLogic
    func displayRootView(viewModel: Splash.CheckRootScreen.ViewModel) {
        debugPrint("viewModel.initialView : \(viewModel.initialView)")
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
            guard let weakSelf = self else { return }
            switch viewModel.initialView {
            case .home:
                weakSelf.router?.routeToHome()
            case .pinLogin: () // TODO: handle show pin pass
            case .resigter: () // TODO: handle show register page
            }
        }
	}
}
