//
//  SplashPresenter.swift
//  ExsampleAppCoordinator
//
//  Created by Komsit on 18/11/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
    func presentRootView(response: Splash.CheckRootScreen.Response)
}

final class SplashPresenter: SplashPresentationLogic {
	weak var viewController: SplashDisplayLogic?
	
	// MARK: Do something
	
    func presentRootView(response: Splash.CheckRootScreen.Response) {
        let initialView: Splash.CheckRootScreen.InitialView
        if !response.isLogin {
            initialView = .pinLogin
        } else {
            initialView = .home
        }
        
        let viewModel = Splash.CheckRootScreen.ViewModel(initialView: initialView)
        viewController?.displayRootView(viewModel: viewModel)
	}
}


