//
//  SplashModels.swift
//  ExsampleAppCoordinator
//
//  Created by Komsit on 18/11/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Splash {
	// MARK: Use cases
    enum CheckRootScreen {
        struct Request { }
        
        struct Response {
            var isLogin: Bool
            var isRegister: Bool
        }
        
        struct ViewModel {
            var initialView: InitialView
        }
        
        enum InitialView {
            case pinLogin
            case resigter
            case home
        }
    }
}
