//
//  HomeRouter.swift
//  ExsampleAppCoordinator
//
//  Created by Komsit on 20/11/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
	func routeToDetail(presentMode flag: Bool)
}

protocol HomeDataPassing {
	var dataStore: HomeDataStore? { get }
}

protocol HomeCoordinator {
    var coordinator: AppCoordinator? { get set }
}

final class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing, HomeCoordinator {
	weak var viewController: HomeViewController?
    weak var coordinator: AppCoordinator?
	var dataStore: HomeDataStore?
	
	// MARK: Routing
    func routeToDetail(presentMode flag: Bool) {
        if let coordinator = coordinator {
            coordinator.goToDetail(param: dataStore?.detailParam ?? "",
                                   isPresent: flag)
        }
    }
}

